FROM python:3.9-slim
WORKDIR /app

RUN pip install pandas redis

COPY ../data/zipcode_demographics.csv /app/data/zipcode_demographics.csv

COPY load_redis_host.py .

CMD ["python", "load_redis_host.py"]